### ISSUE TITLE
Raises error "Assertion Failed: argument is undefined or null" when data is in Fortran order

### ISSUE THREAD

**Issue by Aramist** [haochengxia/vscode-numpy-viewer#1]
To reproduce:

`import numpy as np`
`np.save('works.npy', np.array([[1,2],[3,4]], order='C'))`
`np.save('broken.npy', np.array([[1,2],[3,4]], order='F'))`

**Comment by Aramist** [comment]
Ah, just looked through the source code and saw that this wasn't supported yet.

**Comment by haochengxia** [comment]
Dear Aramist, I have supported the display of data stored in Fortran order in the recently updated version of the plugin (v0.0.7).

I did not implement this feature in the historical version due to usage habits and conversion performance overhead issues. But now I have added this feature and can decide whether to enable the conversion via `vscode-numpy-viewer.fortran2CLikeOrder`(true by default).

To be more specific, for file `example.npy` created by `np.save('example.npy', np.array(np.arange(1, 7).reshape(2, 3), order='F'))`
```
// vscode-numpy-viewer.fortran2CLikeOrder = true, 
[[1, 2, 3], [4, 5, 6]]

// vscode-numpy-viewer.fortran2CLikeOrder = false, 
[[1, 4], [2, 5], [3, 6]]
```
(They are transposed to each other).

Thank you very much for the issue! I will also synchronize relevant updates with you. Any practical advices would be appreciated.
