### ISSUE TITLE
Add function to display shapes or dict items?

### ISSUE THREAD

**Issue by deeptimhe** [haochengxia/vscode-numpy-viewer#5]
Hi, could you please add function to display shapes / dict items? Since the number only is not human-readable.
Many thanks.

**Comment by haochengxia** [comment]
Thanks for your suggestion! Displaying shapes would be added in the next version as optional configuration.
And what does the dict item refer to? Any useful information would be appreciated.

**Comment by deeptimhe** [comment]
> Thanks for your suggestion! Displaying shapes would be added in the next version as optional configuration. And what does the dict item refer to? Any useful information would be appreciated.

dict item that I mean just in the case of dict type in the *.np files.

**Comment by haochengxia** [comment]
'displaying shapes' has been added to the menu as a new command. However, since `dict type` is serialized with pickle, it is not easy to read without a python environment, if you really need this feature, [vscode-pydata-viewer](https://marketplace.visualstudio.com/items?itemName=Percy.vscode-pydata-viewer) may be an option.
